Added profile button functionality #49
pratyushmp/Batua pull request #70
Opened 2021-03-30 17:23 UTC by Borahb

# Description :

Added profile page with profile button functionality.

## Fixes : #49 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/pratyushmp/Batua/blob/main/Contributing.md)?

- [x] Yes
- [ ] No

## Type of change :

_Please delete/edit options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist :

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

https://user-images.githubusercontent.com/49881148/113032390-739d7200-91ad-11eb-9d7d-81738caca65a.mp4

2021-04-01 11:15 UTC, infiniteoverflow approved these changes

2021-04-01 11:38 UTC, pratyushmp requested changes

2021-04-01 11:38 UTC, pratyushmp commented on lib/UI/profile.dart
> +                backgroundColor: Colors.blue[800],
Change the button color to  ```secondary_color``` as given in ```constants.dart```

2021-04-02 03:55 UTC, Borahb commented
@pratyushmp  I have made the changes.

2021-04-02 05:49 UTC, pratyushmp approved these changes

2021-04-02 05:49 UTC, merged

2021-04-02 06:02 UTC, Borahb commented
@pratyushmp  Please update the label for this PR.